-- ===========================================================
-- ROCHA FIRME MODA — script de configuração do banco de dados
--
-- COMO USAR (uma vez só):
-- 1. Crie um projeto grátis em https://supabase.com
-- 2. No menu lateral, abra "SQL Editor"
-- 3. Clique em "New query", cole TODO este arquivo, e clique em "Run"
-- 4. Pronto — a tabela é criada já com os 71 produtos do site.
--
-- Depois disso você NUNCA MAIS precisa mexer em SQL. Todo o dia a dia
-- (adicionar, editar, remover produto) é feito pela tela em admin.html.
-- ===========================================================

create table if not exists produtos (
  id          bigint generated by default as identity primary key,
  categoria   text not null,
  nome        text not null,
  slug        text not null unique,
  foto        text,
  preco       numeric(10,2) not null default 0,
  tamanhos    text not null default '',
  cores       text not null default '',
  novo        boolean not null default false,
  descricao   text not null default '',
  ativo       boolean not null default true,
  criado_em   timestamptz not null default now()
);

-- liga a segurança da tabela
alter table produtos enable row level security;

-- qualquer pessoa (o site) pode LER os produtos
drop policy if exists "Leitura publica" on produtos;
create policy "Leitura publica" on produtos
  for select using (true);

-- só quem estiver logado (a lojista, pelo admin.html) pode
-- adicionar, editar ou remover produtos
drop policy if exists "Escrita autenticada" on produtos;
create policy "Escrita autenticada" on produtos
  for all to authenticated using (true) with check (true);

-- apaga produtos de execuções anteriores deste script, pra poder rodar de novo sem duplicar
delete from produtos;

-- os 71 produtos que já existem no site (ponto de partida)
insert into produtos (categoria, nome, slug, foto, preco, tamanhos, cores, novo, descricao, ativo) values
  ('Vestidos', 'Vestido Midi Rocha', 'vestido-midi-rocha', NULL, 229.90, 'P;M;G', 'terracota;vinho', true, 'Fenda lateral, tecido fluido.', true),
  ('Vestidos', 'Vestido Alfaiataria Firme', 'vestido-alfaiataria-firme', NULL, 249.90, 'P;M;G;GG', 'preto;areia', false, 'Cinto na cintura, corte reto.', true),
  ('Vestidos', 'Vestido Curto Canelado', 'vestido-curto-canelado', NULL, 159.90, 'P;M;G', 'preto;verde', false, 'Malha canelada, alças finas.', true),
  ('Vestidos', 'Vestido Longo Envelope', 'vestido-longo-envelope', NULL, 269.90, 'P;M;G', 'offwhite;terracota', false, 'Amarração frontal, caimento leve.', true),
  ('Vestidos', 'Vestido Jeans Rocha', 'vestido-jeans-rocha', NULL, 219.90, '36;38;40;42', 'jeans', false, 'Botões frontais, cinto incluso.', true),
  ('Vestidos', 'Vestido Tricô Firme', 'vestido-trico-firme', NULL, 199.90, 'P;M;G', 'areia;vinho', true, 'Trama aconchegante, gola alta.', true),
  ('Blusas', 'Blusa Manga Bufante', 'blusa-manga-bufante', NULL, 139.90, 'P;M;G', 'offwhite;terracota', true, 'Viscose leve, manga volumosa.', true),
  ('Blusas', 'Blusa Cropped Canelada', 'blusa-cropped-canelada', NULL, 99.90, 'P;M;G', 'preto;vinho;verde', false, 'Malha canelada, caimento justo.', true),
  ('Blusas', 'Blusa Alfaiataria Firme', 'blusa-alfaiataria-firme', NULL, 159.90, 'P;M;G;GG', 'areia;preto', false, 'Gola aberta, tecido estruturado.', true),
  ('Blusas', 'Blusa Ombro a Ombro', 'blusa-ombro-a-ombro', NULL, 119.90, 'P;M;G', 'offwhite;areia', true, 'Decote canoa, toque macio.', true),
  ('Blusas', 'Blusa Amarração Rocha', 'blusa-amarracao-rocha', NULL, 129.90, 'P;M;G', 'terracota;preto', false, 'Nó frontal ajustável.', true),
  ('Blusas', 'Blusa Regata Costela', 'blusa-regata-costela', NULL, 79.90, 'P;M;G', 'preto;terracota;offwhite', false, 'Básica canelada para compor looks.', true),
  ('Calças', 'Calça Alfaiataria Rocha', 'calca-alfaiataria-rocha', NULL, 189.90, '36;38;40;42;44', 'preto;areia;jeans', true, 'Corte reto, cintura alta, tecido encorpado.', true),
  ('Calças', 'Calça Wide Leg Firme', 'calca-wide-leg-firme', NULL, 169.90, '36;38;40;42', 'jeans;preto', false, 'Pernas largas, caimento fluido.', true),
  ('Calças', 'Calça Cargo Utilitária', 'calca-cargo-utilitaria', NULL, 199.90, '38;40;42;44;46', 'areia;verde', false, 'Bolsos funcionais, sarja pesada.', true),
  ('Calças', 'Calça Reta Essencial', 'calca-reta-essencial', NULL, 149.90, '36;38;40;42', 'preto;offwhite;cinza', false, 'Básica versátil para o dia a dia.', true),
  ('Calças', 'Calça Pantalona Vinho', 'calca-pantalona-vinho', NULL, 194.90, '36;38;40', 'vinho', false, 'Alfaiataria fluida em tom vinho.', true),
  ('Calças', 'Calça Sarja Cargo Preta', 'calca-sarja-cargo-preta', NULL, 184.90, '38;40;42;44', 'preto', false, 'Sarja rígida, ajuste cargo.', true),
  ('Body', 'Body Canelado Básico', 'body-canelado-basico', NULL, 89.90, 'P;M;G', 'preto;offwhite;vinho', true, 'Decote redondo, tecido canelado.', true),
  ('Body', 'Body Manga Longa Rocha', 'body-manga-longa-rocha', NULL, 109.90, 'P;M;G', 'preto;terracota', false, 'Gola alta, fecho de pressão.', true),
  ('Body', 'Body Renda Firme', 'body-renda-firme', NULL, 129.90, 'P;M;G', 'offwhite;areia', false, 'Detalhe em renda no decote.', true),
  ('Body', 'Body Alças Finas', 'body-alcas-finas', NULL, 79.90, 'P;M;G', 'preto;vinho;verde', false, 'Básico versátil para compor looks.', true),
  ('Tricot', 'Tricô Trançado Rocha', 'trico-trancado-rocha', NULL, 189.90, 'P;M;G;GG', 'areia;vinho', true, 'Trama trançada, gola redonda.', true),
  ('Tricot', 'Cardigã Firme Botões', 'cardiga-firme-botoes', NULL, 209.90, 'P;M;G', 'marrom;preto', false, 'Abotoamento frontal, bolsos laterais.', true),
  ('Tricot', 'Tricô Gola Alta', 'trico-gola-alta', NULL, 179.90, 'P;M;G', 'cinza;areia', false, 'Aconchegante, ideal para o friozinho.', true),
  ('Tricot', 'Colete Tricô Rocha', 'colete-trico-rocha', NULL, 139.90, 'P;M;G', 'verde;terracota', false, 'Sem manga, ótimo para camadas.', true),
  ('Jaquetas e Casacos', 'Jaqueta Corta-Vento Rocha', 'jaqueta-corta-vento-rocha', NULL, 249.90, 'P;M;G;GG', 'preto;verde', true, 'Impermeável leve, capuz destacável.', true),
  ('Jaquetas e Casacos', 'Casaco Alfaiataria Firme', 'casaco-alfaiataria-firme', NULL, 329.90, 'P;M;G', 'areia;preto', false, 'Lã sintética, corte reto longo.', true),
  ('Jaquetas e Casacos', 'Bomber Rocha Firme', 'bomber-rocha-firme', NULL, 259.90, 'P;M;G', 'preto;vinho', false, 'Punho canelado, forro macio.', true),
  ('Jaquetas e Casacos', 'Trench Coat Firme', 'trench-coat-firme', NULL, 379.90, 'P;M;G;GG', 'areia;offwhite', true, 'Cinto de amarrar, comprimento midi.', true),
  ('Jaquetas e Casacos', 'Colete Acolchoado Rocha', 'colete-acolchoado-rocha', NULL, 179.90, 'P;M;G', 'preto;verde;terracota', false, 'Leve e quentinho, ideal para camadas.', true),
  ('Blazers', 'Blazer Alfaiataria Rocha', 'blazer-alfaiataria-rocha', NULL, 279.90, 'P;M;G;GG', 'preto;areia', true, 'Ombro estruturado, forro interno.', true),
  ('Blazers', 'Blazer Cropped Firme', 'blazer-cropped-firme', NULL, 229.90, 'P;M;G', 'terracota;preto', false, 'Comprimento curto, botão único.', true),
  ('Blazers', 'Blazer Linho Verão', 'blazer-linho-verao', NULL, 249.90, 'P;M;G', 'offwhite;areia', false, 'Tecido leve, caimento solto.', true),
  ('Blazers', 'Blazer Vinho Alongado', 'blazer-vinho-alongado', NULL, 289.90, 'P;M;G;GG', 'vinho', false, 'Corte longo, fechamento cruzado.', true),
  ('Camisas', 'Camisa Social Firme', 'camisa-social-firme', NULL, 159.90, 'P;M;G;GG', 'offwhite;preto', true, 'Algodão encorpado, corte clássico.', true),
  ('Camisas', 'Camisa Seda Rocha', 'camisa-seda-rocha', NULL, 189.90, 'P;M;G', 'terracota;areia', false, 'Toque sedoso, caimento fluido.', true),
  ('Camisas', 'Camisa Xadrez Firme', 'camisa-xadrez-firme', NULL, 169.90, 'P;M;G;GG', 'marrom;verde', false, 'Estampa xadrez, bolso frontal.', true),
  ('Camisas', 'Camisa Cropped Amarrar', 'camisa-cropped-amarrar', NULL, 129.90, 'P;M;G', 'offwhite;vinho', false, 'Nó frontal, comprimento curto.', true),
  ('T-shirts', 'T-shirt Rocha Oversized', 't-shirt-rocha-oversized', NULL, 89.90, 'P;M;G;GG', 'preto;offwhite;areia', true, 'Malha 100% algodão penteado.', true),
  ('T-shirts', 'T-shirt Firme Básica', 't-shirt-firme-basica', NULL, 69.90, 'P;M;G;GG', 'preto;offwhite;cinza;verde', false, 'Corte reto, essencial no armário.', true),
  ('T-shirts', 'T-shirt Selo Estampada', 't-shirt-selo-estampada', NULL, 94.90, 'P;M;G', 'areia;terracota', true, 'Estampa do selo Rocha Firme no peito.', true),
  ('T-shirts', 'T-shirt Longline', 't-shirt-longline', NULL, 99.90, 'P;M;G;GG', 'preto;cinza', false, 'Barra alongada, modelagem urbana.', true),
  ('T-shirts', 'T-shirt Gola V Firme', 't-shirt-gola-v-firme', NULL, 74.90, 'P;M;G', 'offwhite;vinho', false, 'Gola V, toque macio.', true),
  ('T-shirts', 'T-shirt Listrada Rocha', 't-shirt-listrada-rocha', NULL, 84.90, 'P;M;G;GG', 'preto;offwhite', false, 'Listras finas, algodão premium.', true),
  ('Jeans', 'Jeans Mom Rocha', 'jeans-mom-rocha', NULL, 179.90, '36;38;40;42', 'jeans', true, 'Lavagem média, cintura super alta.', true),
  ('Jeans', 'Jeans Reto Firme', 'jeans-reto-firme', NULL, 169.90, '36;38;40;42', 'jeans', false, 'Corte reto clássico, five pockets.', true),
  ('Jeans', 'Jeans Skinny Rocha', 'jeans-skinny-rocha', NULL, 159.90, '36;38;40', 'jeans', false, 'Modelagem justa, elastano leve.', true),
  ('Jeans', 'Jaqueta Jeans Clássica', 'jaqueta-jeans-classica', NULL, 229.90, 'P;M;G;GG', 'jeans', false, 'Lavagem média, botões metálicos.', true),
  ('Macacões', 'Macacão Alfaiataria Firme', 'macacao-alfaiataria-firme', NULL, 259.90, 'P;M;G', 'preto;areia', true, 'Cinto na cintura, perna reta.', true),
  ('Macacões', 'Macacão Jeans Rocha', 'macacao-jeans-rocha', NULL, 239.90, '36;38;40', 'jeans', false, 'Alças reguláveis, bolsos frontais.', true),
  ('Macacões', 'Macacão Curto Canelado', 'macacao-curto-canelado', NULL, 169.90, 'P;M;G', 'preto;vinho', false, 'Malha canelada, alças finas.', true),
  ('Saias', 'Saia Midi Alfaiataria', 'saia-midi-alfaiataria', NULL, 159.90, 'P;M;G', 'preto;areia', true, 'Fenda frontal, cintura alta.', true),
  ('Saias', 'Saia Jeans Rocha', 'saia-jeans-rocha', NULL, 139.90, '36;38;40;42', 'jeans', false, 'Botões frontais, barra desfiada.', true),
  ('Saias', 'Saia Plissada Firme', 'saia-plissada-firme', NULL, 149.90, 'P;M;G', 'terracota;offwhite', false, 'Plissado fino, caimento leve.', true),
  ('Saias', 'Saia Lápis Firme', 'saia-lapis-firme', NULL, 144.90, 'P;M;G;GG', 'preto;vinho', false, 'Corte justo, fenda traseira.', true),
  ('Bolsas e Calçados', 'Bolsa Tote Rocha', 'bolsa-tote-rocha', NULL, 199.90, 'Único', 'marrom;preto', true, 'Couro sintético, alça de ombro.', true),
  ('Bolsas e Calçados', 'Bolsa Transversal Firme', 'bolsa-transversal-firme', NULL, 159.90, 'Único', 'preto;terracota', false, 'Compacta, alça ajustável.', true),
  ('Bolsas e Calçados', 'Sandália Rasteira Rocha', 'sandalia-rasteira-rocha', NULL, 129.90, '34;35;36;37;38;39', 'dourado;preto', false, 'Solado leve, tiras finas.', true),
  ('Bolsas e Calçados', 'Bota Coturno Firme', 'bota-coturno-firme', NULL, 249.90, '34;35;36;37;38;39', 'preto;marrom', false, 'Cano curto, sola tratorada.', true),
  ('Acessórios', 'Cinto Couro Rocha', 'cinto-couro-rocha', NULL, 79.90, 'Único', 'marrom;preto', false, 'Fivela metálica, couro legítimo.', true),
  ('Acessórios', 'Brinco Argola Firme', 'brinco-argola-firme', NULL, 59.90, 'Único', 'dourado', true, 'Banho a ouro, antialérgico.', true),
  ('Acessórios', 'Óculos de Sol Rocha', 'oculos-de-sol-rocha', NULL, 119.90, 'Único', 'preto;marrom', false, 'Proteção UV400, armação leve.', true),
  ('Acessórios', 'Lenço Estampado Firme', 'lenco-estampado-firme', NULL, 69.90, 'Único', 'terracota;areia', false, 'Seda toque macio, estampa exclusiva.', true),
  ('Shorts e Bermudas', 'Short Alfaiataria Rocha', 'short-alfaiataria-rocha', NULL, 119.90, '36;38;40;42', 'preto;areia', true, 'Cintura alta, caimento reto.', true),
  ('Shorts e Bermudas', 'Short Jeans Firme', 'short-jeans-firme', NULL, 99.90, '36;38;40', 'jeans', false, 'Barra desfiada, five pockets.', true),
  ('Shorts e Bermudas', 'Bermuda Cargo Rocha', 'bermuda-cargo-rocha', NULL, 129.90, '38;40;42;44', 'verde;areia', false, 'Bolsos funcionais, sarja leve.', true),
  ('Shorts e Bermudas', 'Short Moletom Firme', 'short-moletom-firme', NULL, 89.90, 'P;M;G', 'preto;cinza', false, 'Conforto para o dia a dia.', true),
  ('Couro', 'Jaqueta Couro Rocha', 'jaqueta-couro-rocha', NULL, 449.90, 'P;M;G', 'preto;marrom', true, 'Couro legítimo, forro interno.', true),
  ('Couro', 'Saia Couro Firme', 'saia-couro-firme', NULL, 259.90, 'P;M;G', 'preto', false, 'Corte reto, zíper traseiro.', true),
  ('Couro', 'Colete Couro Rocha', 'colete-couro-rocha', NULL, 229.90, 'P;M;G', 'marrom;preto', false, 'Sem manga, acabamento rústico.', true);
